-- Secure analytics schema for Sinonimoen Erronka.
-- Designed for local-first analytics with optional Supabase backup.
-- Requires Supabase anonymous auth if the frontend is going to sync remotely.

create table if not exists public.game_sessions (
  id bigint generated by default as identity primary key,
  session_id text not null unique,
  owner_id uuid not null,
  device_id text not null,
  played_at timestamptz not null default now(),
  difficulty smallint,
  players_count integer not null default 0,
  total_questions integer not null default 0,
  failed_answers integer not null default 0,
  completed_rounds integer not null default 0
);

create table if not exists public.game_player_results (
  id bigint generated by default as identity primary key,
  session_id text not null references public.game_sessions(session_id) on delete cascade,
  owner_id uuid not null,
  device_id text not null,
  learner_id text not null,
  player_name text not null,
  player_order integer not null default 1,
  difficulty smallint,
  score integer not null default 0,
  time_seconds numeric(10, 3) not null default 0,
  questions_answered integer not null default 0,
  failed_count integer not null default 0,
  accuracy numeric(5, 2) not null default 0,
  played_at timestamptz not null default now()
);

create table if not exists public.game_fail_events (
  id bigint generated by default as identity primary key,
  session_id text not null references public.game_sessions(session_id) on delete cascade,
  owner_id uuid not null,
  device_id text not null,
  learner_id text not null,
  player_name text not null,
  difficulty smallint,
  word text not null,
  correct_answer text not null,
  selected_answer text not null,
  question_number integer not null,
  played_at timestamptz not null default now()
);

create table if not exists public.game_question_events (
  id bigint generated by default as identity primary key,
  session_id text not null references public.game_sessions(session_id) on delete cascade,
  owner_id uuid not null,
  device_id text not null,
  learner_id text not null,
  player_name text not null,
  difficulty smallint,
  word text not null,
  correct_answer text not null,
  selected_answer text not null,
  question_number integer not null,
  is_correct boolean not null default false,
  played_at timestamptz not null default now()
);

create index if not exists idx_game_sessions_owner_id on public.game_sessions(owner_id);
create index if not exists idx_game_sessions_played_at on public.game_sessions(played_at desc);
create index if not exists idx_game_player_results_owner_id on public.game_player_results(owner_id);
create index if not exists idx_game_player_results_learner_id on public.game_player_results(learner_id);
create index if not exists idx_game_fail_events_owner_id on public.game_fail_events(owner_id);
create index if not exists idx_game_fail_events_word on public.game_fail_events(word);
create index if not exists idx_game_question_events_owner_id on public.game_question_events(owner_id);
create index if not exists idx_game_question_events_learner_id on public.game_question_events(learner_id);
create index if not exists idx_game_question_events_word on public.game_question_events(word);

alter table public.game_sessions enable row level security;
alter table public.game_player_results enable row level security;
alter table public.game_fail_events enable row level security;
alter table public.game_question_events enable row level security;

drop policy if exists game_sessions_select_own on public.game_sessions;
create policy game_sessions_select_own on public.game_sessions
for select
to authenticated
using (owner_id = auth.uid());

drop policy if exists game_sessions_insert_own on public.game_sessions;
create policy game_sessions_insert_own on public.game_sessions
for insert
to authenticated
with check (owner_id = auth.uid());

drop policy if exists game_player_results_select_own on public.game_player_results;
create policy game_player_results_select_own on public.game_player_results
for select
to authenticated
using (owner_id = auth.uid());

drop policy if exists game_player_results_insert_own on public.game_player_results;
create policy game_player_results_insert_own on public.game_player_results
for insert
to authenticated
with check (owner_id = auth.uid());

drop policy if exists game_fail_events_select_own on public.game_fail_events;
create policy game_fail_events_select_own on public.game_fail_events
for select
to authenticated
using (owner_id = auth.uid());

drop policy if exists game_fail_events_insert_own on public.game_fail_events;
create policy game_fail_events_insert_own on public.game_fail_events
for insert
to authenticated
with check (owner_id = auth.uid());

drop policy if exists game_question_events_select_own on public.game_question_events;
create policy game_question_events_select_own on public.game_question_events
for select
to authenticated
using (owner_id = auth.uid());

drop policy if exists game_question_events_insert_own on public.game_question_events;
create policy game_question_events_insert_own on public.game_question_events
for insert
to authenticated
with check (owner_id = auth.uid());
